### ISSUE TITLE
Playground Labs

### ISSUE THREAD

**Issue by MichelleBKlynn** [learn-co-curriculum/swift-arrayMethods-lab#3]
This is just an FYI that for this lab, and for all of the playground labs, at the end of the lab it tells us to check to solution branch to see the solution (presumably to compare our answers). There is also a link to the solution branch after we submit our pull request and are about to move to the next lab. However, the solution branches do not contain the solution. They are last publicly updated with "solution removed". 

For consistency, either the line at the end of the playground labs that instructs students to check the solution (as well as the "solution" button on Learn that pops up after a student submits their lab) should be removed, or the solution branches should actually the solution. IMHO I think the latter is preferable because it's possible for students to write code that has no errors, but is actually incorrect code for the question at hand. They wouldn't have any way of knowing it is wrong code if they're under the impression it is right (since there are no errors). 

Regular labs (that contain tests) prevent students from trying to submit incorrect code by having the tests fail. However, that's not the case with playground labs (since there are no tests to pass, the code could appear fine), which I assume is the exact reason why students are told at the end of the playground labs to check the solution branch.

**Comment by JimCampagno** [comment]
Thanks for this! I think I might have solution videos made for each of these playground files--that way someone doesn't just go to look at the answer. They would be forced to see someone step through the code for 5-10 min. which can be very beneficial.

I appreciate the feedback!

@MichelleBKlynn

**Comment by JimCampagno** [comment]
Been fixing this problem, almost done with updating all of the playground files. Thanks again!

@MichelleBKlynn
